steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
            'run', 'jobs', 'deploy', 'job-quickstart', '--source', '.',
            '--set-env-vars', 'SLEEP_MS=5000', '--set-env-vars', 'FAIL_RATE=0.1',
            '--tasks', '3', '--max-retries', '3',
            '--memory', '512m',
            '--region', 'us-central1', '--project', '$PROJECT_ID'
           ]
